title: RevHub
description: "Інформатика, українська мова та математика для школярів №3 ;)"
baseurl: "/Homework"
url: "https://yaBobJonez.github.io"

theme: just-the-docs
last_edit_timestamp: true
last_edit_time_format: "@ %m/%d/%Y %l:%M %p"

gh_edit_link: true
gh_edit_link_text: "Доповнити цю сторінку"
gh_edit_repository: "https://github.com/yaBobJonez/Homework"
gh_edit_branch: "uni"
gh_edit_source: docs

plugins:
  - jemoji

callouts:
  new:
    title: Що нового
    color: green
